quarkus:
  http:
    port: 8085
  smallrye-openapi:
    info-title: product-svc
    auto-add-security-requirement: false

  swagger-ui:
    always-include: true
    path: /swagger

  datasource:
    db-kind: postgresql
    jdbc:
      # Is set to 5 as we have 112 connections in total
      initial-size: 1
      min-size: 1
      max-size: 5
      url: ${MTOGO_DB_BASE_URL}/product_svc_db
    username: ${MTOGO_DB_USERNAME}
    password: ${MTOGO_DB_PASSWORD}

    transaction-manager:
      default-transaction-timeout: 300s
  hibernate-orm:
    database:
      generation: update


"%dev":
  quarkus:
    log:
      level: INFO
      console:
        json: false
    hibernate-orm:
      database:
        default-schema: "product"

"%prod":
  quarkus:
    hibernate-orm:
      database:
        default-schema: "product"